services:
  kybe-ssh-fun:
    image: reg.kybe.xyz/kybe-pub/kybe-ssh-fun:latest
    container_name: kybe-ssh-fun
    ports:
      - "2222:2222"
    volumes:
      # ssh-keygen -t ed25519 -f ./ssh_host_ed25519_key -N ""
      - ./ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key:ro
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 256m
        reservations:
          cpus: 0.2
